language: c
addons:
  apt:
    sources:
    - george-edison55-precies-backports
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - cmake-data
    - gcc-4.8
    - clang
    - check
    - libsubunit-dev
dist: trusty
compiler:
- gcc
- clang

git:
  submodules: false
install:
- if [ "$CC" = "gcc" ]; then export CC="gcc-4.8"; fi
before_script:
- mkdir build
- cd build
- cmake ..
script: make
